### ISSUE TITLE
Fix Newsletter Signup Page Style

### ISSUE THREAD

**Issue by bebopkid** [fabricatorzorg/fabricatorz.org#9]
The Mailchimp archive code isn't matching the main site css e.g., links bolden on hover, aren't in Lekton, etc. fabricatorz.org/signup

**Comment by rejon** [comment]
will look at

**Comment by rejon** [comment]
removed the stylesheet line: .display_archive {font-family: arial,verdana; font-size: 12px;} 

created the new style...

nuked...basic css
